# START CROSS DRIVER CONFIG
[drivers.local]
type = "files"
root_path = "/data/local"

[drivers.remote]
type = "kafka"
bootstrap = "kafka:9092"

[[forward]]
from = "local/source-topic"
to   = "remote/dest-topic"

[[forward]]
from = "local/topic-a"
to   = "remote/topic-b"
# END CROSS DRIVER CONFIG
